live_config_reload = true

[env]
TERM = 'xterm-256color'

# Colors (Kanagawa Dragon)
# https://github.com/alacritty/alacritty-theme/blob/master/themes/kanagawa_dragon.toml

[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.dim]
black = '#0d0c0c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#C8C093'
yellow = '#c4b28a'

[colors.normal]
black = '#0d0c0c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#C8C093'
yellow = '#c4b28a'

[colors.bright]
black = '#a6a69c'
blue = '#7FB4CA'
cyan = '#7AA89F'
green = '#87a987'
magenta = '#938AA9'
red = '#E46876'
white = '#c5c9c5'
yellow = '#E6C384'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

[colors.cursor]
cursor = "#d8dee9"
text = "#202329"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#202329"

[font]
size = 12

[font.bold]
family = "MonaspiceRn Nerd Font"
#family = "Recursive Mono Casual Static"
style = "Bold"

[font.italic]
family = "MonaspiceRn Nerd Font"
#family = "Recursive Mono Casual Static"
style = "ExtraLight Italic"

[font.normal]
family = "MonaspiceRn Nerd Font"
#family = "Recursive Mono Casual Static"
style = "Light"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "`n"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "`x"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "`K"
key = "K"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "`,"
key = "H"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "`."
key = "L"
mods = "Alt|Control"

[window]
opacity = 0.8

[window.padding]
x = 25
y = 8
