{
  imports = [
    ./apps.nix
    ./backup.nix
    ./bluetooth.nix
    ./fonts.nix
    ./display.nix
    ./i18n.nix
    ./keyboards
    ./networking.nix
    ./os.nix
    ./mouse.nix
    ./power.nix
    ./security.nix
    ./sound.nix
    ./tools.nix
    ./virtualization.nix
  ];
}
